import type { WebhookEvent, MessageEvent, TextEventMessage } from '@line/bot-sdk';

// Re-export LINE types for convenience
export type { WebhookEvent, MessageEvent, TextEventMessage };

// Chat message stored in DynamoDB
export interface ChatMessage {
  role: 'user' | 'assistant' | 'system';
  content: string;
  timestamp: number;
}

// Chat history record in DynamoDB
export interface ChatHistory {
  userId: string;
  messages: ChatMessage[];
  createdAt: number;
  updatedAt: number;
  ttl: number; // DynamoDB TTL for auto-expiration
}

// OpenAI message format
export interface OpenAIMessage {
  role: 'user' | 'assistant' | 'system';
  content: string;
}

// Lambda API Gateway event (simplified)
export interface APIGatewayEvent {
  body: string | null;
  headers: Record<string, string | undefined>;
  httpMethod: string;
  path: string;
  queryStringParameters: Record<string, string | undefined> | null;
}

// Lambda API Gateway response
export interface APIGatewayResponse {
  statusCode: number;
  headers?: Record<string, string>;
  body: string;
}

// Raw message stored in Supabase for permanent storage and analytics
export interface RawMessage {
  id?: number;                // Auto-generated primary key
  message_id: string;         // Unique message ID (webhookEventId or generated)
  user_id: string;            // LINE user ID
  event_type: string;         // message, postback, follow, unfollow, etc.
  source_type: string;        // user, group, room
  raw_event: WebhookEvent;    // Complete raw LINE webhook event (stored as JSONB)
  timestamp: number;          // Event timestamp from LINE
  received_at: string;        // ISO timestamp when we received the event
  created_at?: string;        // Auto-generated by Supabase
}
