import type { WebhookEvent, MessageEvent, TextEventMessage } from '@line/bot-sdk';

// Re-export LINE types for convenience
export type { WebhookEvent, MessageEvent, TextEventMessage };

// Chat message stored in DynamoDB
export interface ChatMessage {
  role: 'user' | 'assistant' | 'system';
  content: string;
  timestamp: number;
}

// Chat history record in DynamoDB
export interface ChatHistory {
  userId: string;
  messages: ChatMessage[];
  createdAt: number;
  updatedAt: number;
  ttl: number; // DynamoDB TTL for auto-expiration
}

// OpenAI message format
export interface OpenAIMessage {
  role: 'user' | 'assistant' | 'system';
  content: string;
}

// Lambda API Gateway event (simplified)
export interface APIGatewayEvent {
  body: string | null;
  headers: Record<string, string | undefined>;
  httpMethod: string;
  path: string;
  queryStringParameters: Record<string, string | undefined> | null;
}

// Lambda API Gateway response
export interface APIGatewayResponse {
  statusCode: number;
  headers?: Record<string, string>;
  body: string;
}

// Raw message stored in Supabase for permanent storage and analytics
export interface RawMessage {
  id?: number;                // Auto-generated primary key
  message_id: string;         // Unique message ID (webhookEventId or generated)
  user_id: string;            // LINE user ID
  event_type: string;         // message, postback, follow, unfollow, etc.
  source_type: string;        // user, group, room
  raw_event: WebhookEvent;    // Complete raw LINE webhook event (stored as JSONB)
  timestamp: number;          // Event timestamp from LINE
  received_at: string;        // ISO timestamp when we received the event
  created_at?: string;        // Auto-generated by Supabase
}

// ============================================
// Analytics types
// ============================================

// Conversation session tracking
export interface Conversation {
  id?: number;
  user_id: string;
  started_at: string;
  ended_at?: string;
  message_count: number;
  agents_used: string[];
  had_crisis: boolean;
  created_at?: string;
}

// Message stored for analytics
export interface AnalyticsMessage {
  id?: number;
  conversation_id?: number;
  user_id: string;
  role: 'user' | 'assistant';
  content: string;
  message_type?: string;
  agent_type?: string;
  response_time_ms?: number;
  timestamp: number;
  created_at?: string;
}

// Agent routing decision
export interface AgentRouting {
  id?: number;
  message_id?: number;
  user_message: string;
  routed_to: string;
  routing_reason?: 'keyword' | 'llm_decision' | 'postback';
  keywords_matched?: string[];
  confidence?: number;
  created_at?: string;
}

// Expert interaction tracking
export interface ExpertInteraction {
  id?: number;
  user_id: string;
  action: 'search' | 'view' | 'select' | 'book';
  search_query?: string;
  expert_id?: number;
  expert_name?: string;
  expert_domains?: string[];
  results_count?: number;
  created_at?: string;
}

// RAG query tracking
export interface RagQuery {
  id?: number;
  user_id: string;
  query: string;
  index_name: string;
  results_count: number;
  top_score?: number;
  sources?: string[];
  was_helpful?: boolean;
  created_at?: string;
}

// Crisis event tracking
export interface CrisisEvent {
  id?: number;
  user_id: string;
  message_content: string;
  detection_keywords: string[];
  response_sent: boolean;
  notification_sent: boolean;
  created_at?: string;
}

// Daily aggregated metrics
export interface DailyMetrics {
  id?: number;
  date: string;
  total_messages: number;
  unique_users: number;
  new_users: number;
  conversations_started: number;
  avg_messages_per_conversation?: number;
  avg_response_time_ms?: number;
  agent_distribution?: Record<string, number>;
  crisis_count: number;
  expert_searches: number;
  expert_bookings: number;
  rag_queries: number;
  created_at?: string;
}
